name: stop-deployment # ワークフローの名前を指定
on:
  schedule:
    - cron: '10 0 * * *' # 毎週月曜日から金曜日の17時にワークフローをトリガー
  timezone: 'Asia/Tokyo' # タイムゾーンを日本時間に設定
  workflow_dispatch: # 手動でワークフローをトリガーするためのオプション

  
jobs:
  build:
    runs-on: ubuntu-latest # ジョブが実行される環境を指定
    steps:
      - uses: actions/checkout@v2 # コードをチェックアウトするアクション
      - name: Install Railway CLI # APIコードを呼び出すステップ
        run: npm i -g @railway/cli #Node.js ver 16 以上が必要
      - name: Stop on Railway
        env:
          API_KEY: ${{ secrets.RAILWAY_TOKEN }} # APIキーを環境変数として設定
        run: 
          run: railway down --service ${{ secrets.RAILWAY_SERVICE_NAME }}