name: stop-deployment # ワークフローの名前を指定
on:
  schedule:
    - cron: '37 15 * * *' # 毎週月曜日から金曜日の17時にワークフローをトリガー
  workflow_dispatch: # 手動でワークフローをトリガーするためのオプション

  
jobs:
  stop:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest # Railway公式のツールボックスを直接使う
    steps:
      - name: Stop Railway Service
        shell: sh
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          export CI=true
          railway down --service ${{ secrets.RAILWAY_SERVICE_NAME }}