name: stop-deployment # ワークフローの名前を指定
on:
  schedule:
    - cron: '28 15 * * *' # 毎週月曜日から金曜日の17時にワークフローをトリガー
  workflow_dispatch: # 手動でワークフローをトリガーするためのオプション

  
jobs:
  build:
    runs-on: ubuntu-latest # ジョブが実行される環境を指定
    steps:
      - uses: actions/checkout@v4 # コードをチェックアウトするアクション
      - name: Install Railway CLI # APIコードを呼び出すステップ
        run: npm i -g @railway/cli #Node.js ver 16 以上が必要
      - name: Stop on Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # APIキーを環境変数として設定
        run: railway down -y --service ${{ secrets.RAILWAY_SERVICE_NAME }}